import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import ReduxProvider from "../redux/ReduxProvider";
import Header from "../components/header/Header";
import { Footer } from "../components/footer/Footer";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={rubik.variable}>
      <body className="font-sans bg-[#E7E7E3] text-foreground antialiased"
      data-new-gr-c-s-check-loaded="14.1274.0"
      data-gr-ext-installed=""
      >
        <ReduxProvider>
          <Header />
          {children}
          <Footer/>
        </ReduxProvider>
      </body>
    </html>
  );
}