import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import ReduxProvider from "../redux/ReduxProvider";
import Header from "../components/header/Header";
import Footer from "../components/footer/Footer";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Kicks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={rubik.variable}>
      <body className="font-sans bg-[#E7E7E3] text-foreground antialiased"
        data-new-gr-c-s-check-loaded="14.1274.0"
        data-gr-ext-installed=""
      >
        <ReduxProvider>
          <Header />
          <Toaster position="bottom-right" />
          <div className="min-h-screen">{children}</div>
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}




